"use client";

import * as React from "react";
import { cn } from "@/lib/cn";

export type ModelId = "chatgpt" | "claude" | "gemini" | "grok";

const MODELS: { id: ModelId; label: string }[] = [
  { id: "chatgpt", label: "ChatGPT" },
  { id: "claude", label: "Claude" },
  { id: "gemini", label: "Gemini" },
  { id: "grok", label: "Grok" },
];

const ALL_MODEL_IDS = MODELS.map((m) => m.id);

function useModelSelection(
  exclusive: boolean,
  initialExclusive: ModelId | null,
) {
  const [selected, setSelected] = React.useState<Set<ModelId>>(() => {
    if (exclusive && initialExclusive) return new Set<ModelId>([initialExclusive]);
    return new Set<ModelId>(["chatgpt", "claude", "gemini", "grok"]);
  });

  const toggle = (id: ModelId) => {
    setSelected((prev) => {
      const next = new Set(prev);
      if (exclusive) {
        next.clear();
        next.add(id);
        return next;
      }
      if (next.has(id)) next.delete(id);
      else next.add(id);
      return next;
    });
  };

  return { selected, toggle };
}

type ModelToggleProps = {
  className?: string;
  label?: string;
};

type ModelToggleRowProps = ModelToggleProps & {
  models?: readonly ModelId[];
  value?: ModelId[];
  onChange?: (next: ModelId[]) => void;
};

export function ModelToggleRow({
  className,
  label = "MODELS:",
  models,
  value,
  onChange,
}: ModelToggleRowProps) {
  const entries = React.useMemo(() => {
    const list = models ?? ALL_MODEL_IDS;
    return MODELS.filter((m) => list.includes(m.id));
  }, [models]);

  const [internal, setInternal] = React.useState<ModelId[]>(() =>
    entries.map((m) => m.id),
  );

  const selectedList = value ?? internal;

  const toggleRow = (id: ModelId) => {
    const set = new Set(selectedList);
    if (set.has(id)) set.delete(id);
    else set.add(id);

    let next = entries.map((m) => m.id).filter((mid) => set.has(mid));
    if (next.length === 0) next = selectedList;

    if (onChange) onChange(next);
    else setInternal(next);
  };

  return (
    <div className={cn("flex flex-wrap items-center gap-3", className)}>
      <span className="text-[11px] font-semibold uppercase tracking-wider text-muted">
        {label}
      </span>
      <div className="flex flex-wrap gap-2">
        {entries.map(({ id, label: text }) => {
          const on = selectedList.includes(id);
          return (
            <button
              key={id}
              type="button"
              onClick={() => toggleRow(id)}
              className={cn(
                "rounded-lg border px-3 py-1.5 text-sm transition-colors",
                on
                  ? "border-white bg-white text-black"
                  : "border-border-subtle bg-surface-raised text-on-surface hover:border-outline",
              )}
            >
              {text}
            </button>
          );
        })}
      </div>
    </div>
  );
}

/** Session footer style: pill toggles, single active. */
export function GeneratedByToggle({ className }: { className?: string }) {
  const { selected, toggle } = useModelSelection(true, "gemini");

  return (
    <div className={cn("flex flex-wrap items-center gap-2", className)}>
      <span className="text-[11px] font-semibold uppercase tracking-wider text-muted">
        Generated by
      </span>
      <div className="flex flex-wrap gap-2">
        {MODELS.filter((m) => m.id !== "grok").map(({ id, label: text }) => {
          const on = selected.has(id);
          return (
            <button
              key={id}
              type="button"
              onClick={() => toggle(id)}
              className={cn(
                "rounded-full border px-3 py-1 text-sm transition-colors",
                on
                  ? "border-white bg-white text-black"
                  : "border-border-subtle text-muted hover:text-on-surface",
              )}
            >
              {text}
            </button>
          );
        })}
      </div>
    </div>
  );
}
